### ISSUE TITLE
Move `summrt` to own repo

### ISSUE THREAD

**Issue by athowes** [epistorm/rt-collabathon-2024#2]
I'd advocate for different projects having their own repo. I think it'd be overwhelming to deal with issues and PRs if all 40 attendees are putting work into this repo. What do you think @gvegayon?

**Comment by athowes** [comment]
Also if we want this to be used by anyone surely at some point it'll be in its own repo so better to just start that way IMO.

**Comment by gvegayon** [comment]
Now lives at https://github.com/EpiForeSITE/summrt
